import Ajv from 'ajv';
import * as schemaGenericRequest from './schema_generic-request.json';
import * as schemaGetAppDataRequest from './schema_get-app-data-request.json';
import * as schemaStartDisputeRequest from './schema_start-dispute-request.json';
import * as schemaGetInvestigationRequest from './schema_get-investigation-results.json';
import * as schemaTradelineDispute from './schema_tradeline-dispute.json';
import * as schemaPublicitemDispute from './schema_public-dispute.json';
import * as schemaPersonalitemDispute from './schema_personal-dispute.json';
import * as schemaGetTrendingDataRequest from './schema_get-trending-data-request.json';
export const ajv = new Ajv();
ajv.addSchema(schemaGenericRequest, 'getRequest');
ajv.addSchema(schemaGetAppDataRequest, 'getAppDataRequest');
ajv.addSchema(schemaStartDisputeRequest, 'startDisputeRequest');
ajv.addSchema(schemaGetInvestigationRequest, 'getInvestigationResultsRequest');
ajv.addSchema(schemaTradelineDispute, 'disputeTradeline');
ajv.addSchema(schemaPublicitemDispute, 'disputePublicitem');
ajv.addSchema(schemaPersonalitemDispute, 'disputePersonalitem');
ajv.addSchema(schemaGetTrendingDataRequest, 'getTrendingDataRequest');
