# NOTE: update this with your service name
service: credit-report-service-resources

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

custom:
  settings:
    IDENTITY_IDS:
      dev: 'us-east-2:69169c15-c0c4-4e0b-886c-4afab307e612'
      qa: 'us-east-2:69169c15-c0c4-4e0b-886c-4afab307e612'
      prod: 'us-east-2:ea31caf7-0945-4607-a3c4-0c9942967a32'
    POOL_IDS:
      dev: 'us-east-2_beTcykTM9'
      qa: 'us-east-2_beTcykTM9'
      prod: 'us-east-2_R22DawoAR'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  environment:
    OUR_ENV: ${self:provider.stage}

resources:
  Resources:
    CreditReports:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: 'userId'
            AttributeType: 'S'
          - AttributeName: 'version'
            AttributeType: 'N'
        KeySchema:
          - AttributeName: 'userId'
            KeyType: 'HASH'
          - AttributeName: 'version'
            KeyType: 'RANGE'
        BillingMode: PAY_PER_REQUEST
        TableName: CreditReports
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: credit-reports-authorizer
        Type: COGNITO_USER_POOLS
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        ProviderARNs:
          - !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${self:custom.settings.POOL_IDS.${opt:stage}}'

  Outputs:
    CreditReportsTable:
      Description: 'Credit reports table'
      Value: !Ref CreditReports
      Export:
        Name: !Sub '${self:service}-credit-reports'
    CreditReportsTableStreamArn:
      Value: { 'Fn::GetAtt': ['CrediReports', 'StreamArn'] }
      Export:
        Name: !Sub '${self:service}-credit-reports-stream'
    ApiGatewayAuthorizorId:
      Description: 'Credit reports API gateway authorizer'
      Value: !Ref ApiGatewayAuthorizer
      Export:
        Name: !Sub '${self:service}-credit-reports-authorizer'
