# NOTE: update this with your service name
service: web-api-resources

custom:
  settings:
    IDENTITY_IDS:
      dev: 'us-east-2:69169c15-c0c4-4e0b-886c-4afab307e612'
      qa: 'us-east-2:69169c15-c0c4-4e0b-886c-4afab307e612'
      staging: 'us-east-2:211dd2a1-db37-4632-a4da-d05c08a80c47'
      prod: 'us-east-2:ea31caf7-0945-4607-a3c4-0c9942967a32'
    POOL_IDS:
      dev: 'us-east-2_beTcykTM9'
      qa: 'us-east-2_beTcykTM9'
      staging: 'us-east-2_80pbK9Kx7'
      prod: 'us-east-2_R22DawoAR'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  environment:
    OUR_ENV: ${self:provider.stage}

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:provider.stage}-web-app-api
        MinimumCompressionSize: 1024

    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: web-app-authorizer
        Type: COGNITO_USER_POOLS
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        ProviderARNs:
          - !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${self:custom.settings.POOL_IDS.${opt:stage}}'

    InitiativeResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: !Ref ApiGatewayRestApi
        ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
        PathPart: 'initiatives'

    APITopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: APITopic

    DeadLetterQueue:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: lambdadeadletterqueue

  Outputs:
    ApiGatewayRestApiId:
      Description: 'Web App API id'
      Value: !Ref ApiGatewayRestApi
      Export:
        Name: !Sub '${self:service}-apigw-id'
    ApiGatewayRestApiResourceId:
      Description: 'Web App API root resource'
      Value: !GetAtt ApiGatewayRestApi.RootResourceId
      Export:
        Name: !Sub '${self:service}-apigw-rootresource'
    ApiGatewayRestApiInitiativeResourceId:
      Description: 'Web App API root resource id'
      Value: !Ref InitiativeResource
      Export:
        Name: !Sub '${self:service}-apigw-initiativeresource'
    ApiGatewauAuthorizerId:
      Description: 'Web App API authorizer id'
      Value: !Ref ApiGatewayAuthorizer
      Export:
        Name: !Sub '${self:service}-apigw-authorizer'

    APITopic:
      Description: 'API Topic for general use'
      Value: !Ref APITopic
      Export:
        Name: !Sub '${self:provider.stage}-api-endpoints-api-topic'
